### ISSUE TITLE
this code can not run?

### ISSUE THREAD

**Issue by tcoln** [aitangbodan/water_line_detection#1]
follow your steps, it doesn't work?
Traceback (most recent call last):
  File "tools/eval.py", line 130, in <module>
    main()
  File "tools/eval.py", line 59, in main
    model = model = models.pidnet.get_seg_model(config, imgnet_pretrained=False)
  File "/mnt/data/glt/safep/ponding/water_line_detection/tools/../models/pidnet.py", line 206, in get_seg_model
    pretrained_dict = torch.load(cfg.MODEL.PRETRAINED, map_location='cpu')
  File "/mnt/data/glt/.local/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/mnt/data/glt/.local/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/mnt/data/glt/.local/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained_models/imagenet/PIDNet_S_ImageNet.pth.tar'

**Comment by Jameshualin** [comment]
waterline_detection的预训练权重在哪里呀？pretrained_models/0.001.pt就是这个，没有训练权重，模型无法训练吧？
请问可以提供水岸线提取的预训练权重吗？

**Comment by Jameshualin** [comment]
waterline_detection的预训练权重在哪里呀？pretrained_models/0.001.pt就是这个，没有训练权重，模型无法训练吧？
请问可以提供水岸线提取的预训练权重吗？
